2023-10-17 18:53:05,009 - ERROR - api:1455 - Exception on /journalsplos/search [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/api/book/journalsplos.py", line 74, in get
    data = search.search(keyword=keyword, category=category, filterstartdate=start,
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/controller/book/journalsplos/search.py", line 87, in search
    maxpage = search_results["numFound"] / sizepage
TypeError: unsupported operand type(s) for /: 'int' and 'str'
2023-10-17 19:16:30,401 - ERROR - api:1455 - Exception on /journalsplos/search [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/api/book/journalsplos.py", line 74, in get
    data = search.search(keyword=keyword, category=category, filterstartdate=start,
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/controller/book/journalsplos/search.py", line 94, in search
    ftc = [caption.rstrip().lstrip()
TypeError: 'NoneType' object is not iterable
2023-10-17 19:18:38,663 - ERROR - api:1455 - Exception on /journalsplos/search [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/api/book/journalsplos.py", line 74, in get
    data = search.search(keyword=keyword, category=category, filterstartdate=start,
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/controller/book/journalsplos/search.py", line 94, in search
    ftc = [caption.rstrip().lstrip()
TypeError: 'NoneType' object is not iterable
2023-10-17 20:07:18,843 - ERROR - api:1455 - Exception on /journalsplos/search [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/api/book/journalsplos.py", line 74, in get
    data = search.search(keyword=keyword, category=category, filterstartdate=start,
  File "/home/ubuntu/Desktop/TRAINING/api-downloader/controller/book/journalsplos/search.py", line 89, in search
    id = doc.get("id", "")
UnboundLocalError: local variable 'doc' referenced before assignment
2023-10-19 19:19:45,656 - ERROR - api:1455 - Exception on /librarybpk/search [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/ubuntu/Desktop/api-downloader/api/book/librarybpk.py", line 30, in get
    data = search.search(
  File "/home/ubuntu/Desktop/api-downloader/controller/book/librarybpk/search.py", line 129, in search
    raw_datas[key] = value
TypeError: unhashable type: 'PyQuery'
2023-10-22 20:19:50,877 - ERROR - api:1455 - Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 407, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 430, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Boolean is not JSON serializable
2023-10-22 20:21:31,539 - ERROR - api:1455 - Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 407, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 430, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Boolean is not JSON serializable
2023-10-22 20:27:18,488 - ERROR - api:1455 - Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 407, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 430, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Boolean is not JSON serializable
2023-10-22 20:29:20,496 - ERROR - api:1455 - Exception on /swagger.json [GET]
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 407, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 430, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Boolean is not JSON serializable
2023-10-22 20:30:10,358 - ERROR - flask_restx.api:576 - Unable to render schema
Traceback (most recent call last):
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/api.py", line 571, in __schema__
    self._schema = Swagger(self).as_dict()
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/swagger.py", line 239, in as_dict
    serialized = self.serialize_resource(
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/swagger.py", line 438, in serialize_resource
    doc = self.extract_resource_doc(resource, url, route_doc=route_doc)
  File "/home/ubuntu/Desktop/api-downloader/.venv/lib/python3.10/site-packages/flask_restx/swagger.py", line 350, in extract_resource_doc
    key = (name, param.get("in", "query"))
AttributeError: 'Boolean' object has no attribute 'get'
